import './globals.css'
import { nanum_gothic } from './fonts.js'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={nanum_gothic.className}>{children}</body>
    </html>
  )
}
